fix(datastore): quote table name in create table-references SQL statement
aws-amplify/amplify-ios pull request #1485
Opened 2021-10-23 01:03 UTC by diegocstn

*Issue #, if available:*
#1477 

*Description of changes:*
Quote table name in create table-references SQL statement. 
Ref: [SQLite keywords](https://www.sqlite.org/lang_keywords.html)

*Check points: (check or cross out if not relevant)*

- [x] Added new tests to cover change, if needed
- [ ] Build succeeds with all target using Swift Package Manager
- [x] All unit tests pass
- [x] All integration tests pass
~- [ ] Documentation update for the change if required~
- [x] PR title conforms to conventional commit style

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-11-04 16:43 UTC, HuiSF approved these changes

2021-11-12 17:30 UTC, lawmicha approved these changes

2021-12-01 14:46 UTC, lawmicha requested changes
Is this rebased with the migration related sql statements? Do we need to update those statements as well?

2021-12-02 16:49 UTC, lawmicha approved these changes

2021-12-21 01:52 UTC, merged