chore: fix unit tests workflow
aws-amplify/amplify-ios pull request #1880
Opened 2022-06-08 19:35 UTC by ruisebas

*Description of changes:*
- Fixing `.github/composite_actions/run_xcodebuild_test/action.yml` to actually run the scheme passed in the input
- Adding `AmplifyTests` to the `Amplify` scheme

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-06-08 20:07 UTC, phantumcode approved these changes

2022-06-09 17:37 UTC, harsh62 approved these changes

2022-06-09 17:41 UTC, ameter requested changes

2022-06-09 17:41 UTC, ameter commented on .github/composite_actions/run_xcodebuild_test/action.yml
> +        xcodebuild test -scheme ${{ inputs.scheme }} -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13' | xcpretty --simple --color --report junit && exit ${PIPESTATUS[0]}
Should we pipe this through an environment variable?  I know we (people with write access to the repo) should be the only ones able to control the input here, but we're still using it directly in a bash substitution, so I think reading it into an environment variable and then referencing that in the bash line would be safer

2022-06-09 21:31 UTC, ameter approved these changes

2022-06-10 15:00 UTC, merged