Makes AsyncStream conform to Sendable when Element is Sendable
aws-amplify/amplify-ios pull request #2168
Opened 2022-08-17 22:53 UTC by brennanMKE

*Issue #, if available:*

*Description of changes:*

This will only apply to older Swift compilers so that this code builds with Xcode 13.2.1. The code below is what declares the `@unchecked Sendable` conformance which is added in the next version of Swift.

```swift
#if swift(<5.6)
extension AsyncStream: @unchecked Sendable where Element: Sendable { }
extension AsyncThrowingStream: @unchecked Sendable where Element: Sendable { }
#endif
```

*Check points: (check or cross out if not relevant)*

- [ ] Added new tests to cover change, if needed
- [ ] Build succeeds with all target using Swift Package Manager
- [ ] All unit tests pass
- [ ] All integration tests pass
- [ ] Security oriented best practices and standards are followed (e.g. using input sanitization, principle of least privilege, etc)
- [ ] Documentation update for the change if required
- [ ] PR title conforms to conventional commit style
- [ ] If breaking change, documentation/changelog update with migration instructions

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-08-17 23:04 UTC, ameter approved these changes

2022-08-17 23:07 UTC, ameter requested changes
some tests are failing

2022-08-17 23:58 UTC, lawmicha reviewed
rebased from `dev-preview` to get the changes with APIPlugin async APIs and the subscription tests are working

2022-08-17 23:59 UTC, lawmicha approved these changes

2022-08-26 16:27 UTC, brennanMKE commented
We decided to use Xcode 13.4 and Swift 5.6 as our base versions for the V2 release so this change will not be necessary.

2022-08-26 16:27 UTC, closed without merging