fix(datastore-v2): synchronize multiple storageEngine initializations
aws-amplify/amplify-ios pull request #2377
Opened 2022-09-30 00:55 UTC by 5d

*Issue #, if available:*

Fix failed [test cases](https://app.circleci.com/pipelines/github/aws-amplify/amplify-ios/7011/workflows/feab23cf-6c2b-4330-a2e2-d9de7c9b38f2/jobs/48370) for `AWSDataStoreLocalStoreTests`.

*Description of changes:*

Adding a new flag `isStorageEngineInitialized` to synchronize `storageEngine` initialization between multiple threads. 

*Check points: (check or cross out if not relevant)*

- [ ] Added new tests to cover change, if needed
- [ ] Build succeeds with all target using Swift Package Manager
- [ ] All unit tests pass
- [ ] All integration tests pass
- [ ] Security oriented best practices and standards are followed (e.g. using input sanitization, principle of least privilege, etc)
- [ ] Documentation update for the change if required
- [ ] PR title conforms to conventional commit style
- [ ] If breaking change, documentation/changelog update with migration instructions

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-09-30 01:15 UTC, manaswi223 approved these changes
LGTM ✅

2022-09-30 02:09 UTC, lawmicha requested changes
Hi @5d, thanks for working on this!

2022-09-30 02:09 UTC, lawmicha commented on AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/AWSDataStorePlugin.swift
> +                self.isStorageEngineInitialized.set(true)
`DataStore.stop` and `DataStore.clear` will deallocate the storageEngine so I'm thinking this variable should be set back to `false` somewhere in those code paths

2022-09-30 02:53 UTC, lawmicha commented on AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/AWSDataStorePlugin.swift
> -            if storageEngine != nil {
Any DataStore API (save, query, start, etc) will kick off `initStorageEngineAndStartSync` and ignore the completion. Let's say thread1  enters `initStorageEngine` and creates an instance of `storageEngine`, while thread 2 checks `storageEngine != nil` in the first line under `initStorageEngineAndStartSync`. Is it a problem that storageEngine is being read and written to at the same time?

Can we just remove the first line of `initStorageEngineAndStartSync` that returns early if `storageEngine` != nil? And then make `initStorageEngine()` return 3 cases
```
enum InitStorageEngineResult {
  case successfullyInitialized
  case alreadyInitialized
  case failure(DataStoreError)
}
```

where "alreadyInitialized" we don't call startSync and just return successfulVoid which keeps the same behavior as before

2022-10-03 18:06 UTC, lawmicha reviewed
LGTM, the two remaining things left I believe is to run the DataStore integration tests and cherry-pick/manually patch this change over to `main`. For integration tests, i'll take care of that, could you apply this change onto `main` as well? I've started cutting PRs as `fix(datastore-v2)` and `fix(datastore-v1)` to differentiate between them

2022-10-05 02:54 UTC, lawmicha commented
- [ ] Ran AWSDataStorePluginIntegrationTests
- [ ] Ran AWSDataStorePluginV2Tests
- [ ] Ran AWSDataStorePluginMultiAuthTests
- [ ] Ran AWSDataStorePluginCPKTests
- [ ] Ran AWSDataStorePluginAuthCognitoTests
- [ ] Ran AWSDataStorePluginAuthIAMTests

2022-10-05 03:02 UTC, lawmicha approved these changes

2022-10-05 16:42 UTC, merged