refactor(datastore): Support for non codingkey based sort
aws-amplify/amplify-ios pull request #846
Opened 2020-10-21 22:24 UTC by royjit

*Description of changes:* Give support for AWSDatastorePlugin to accept non Coding key based sort input. The public api can be accessed via escape hatch

```swift
public func query<M: Model>(_ modelType: M.Type,
                                modelSchema: ModelSchema,
                                where predicate: QueryPredicate? = nil,
                                sort sortInput: [QuerySortDescriptor]? = nil,
                                paginate paginationInput: QueryPaginationInput? = nil,
                                completion: DataStoreCallback<[M]>)
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2020-10-22 23:02 UTC, palpatim requested changes
This is a breaking change. Please add a new method rather than changing the signature of the existing one.

2020-10-22 23:10 UTC, royjit commented on AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/AWSDataStorePlugin+DataStoreBaseBehavior.swift
> +                                sort sortInput: [QuerySortDescriptor]? = nil,
This method is new, added as part of flutter support for datastore. The original public apis can be checked here - https://github.com/aws-amplify/amplify-ios/blob/main/AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/AWSDataStorePlugin%2BDataStoreBaseBehavior.swift#L60-L91

2020-10-22 23:10 UTC, royjit commented on AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/AWSDataStorePlugin+DataStoreBaseBehavior.swift
> +              sort: sortInput?.covertToSortDescriptor(),
Changed to new name

2020-10-22 23:10 UTC, royjit commented on AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/QuerySort+SQLite.swift
> +    func covertToSortDescriptor() -> [QuerySortDescriptor]? {
Changed to new name

2020-10-23 14:04 UTC, palpatim approved these changes

2020-10-23 14:04 UTC, palpatim commented on AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/AWSDataStorePlugin+DataStoreBaseBehavior.swift
> +                                sort sortInput: [QuerySortDescriptor]? = nil,
Got it, so the diff is against the feature branch, not against main? In that case, I withdraw my objection. :)

2020-10-23 16:14 UTC, ruiguoamz approved these changes
looks good to me since it's just refactoring the code

2020-10-23 18:04 UTC, merged